include:
  - path: ../docker-compose.network.yaml

services:
  idmService:
    build:
      context: .
      dockerfile: idm.dockerfile
    image: idm_service_image
    container_name: ${IDM_HOST}
    depends_on:
      idmDB:
        condition: service_healthy
    environment:
      IDM_PORT: ${IDM_PORT}

      IDM_DB_HOST: ${IDM_DB_HOST}
      IDM_DB_USER: ${IDM_DB_USER}
      IDM_DB_PASSWORD: ${IDM_DB_PASSWORD}
      IDM_DB_NAME: ${IDM_DB_NAME}
      IDM_DB_PORT: ${IDM_DB_PORT}
    restart: always
    networks:
      - idm-network
      - pos-network

  idmDB:
    image: postgres:16.10-alpine3.22
    container_name: ${IDM_DB_HOST}
    volumes:
      - idm_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${IDM_DB_PASSWORD}
      POSTGRES_USER: ${IDM_DB_USER}
      POSTGRES_DB: ${IDM_DB_NAME}
    restart: always
    networks:
      - idm-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${IDM_DB_USER} -d ${IDM_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  idm-network:
    name: idm-network
    driver: bridge

volumes:
  idm_db:
    driver: local
