name: event
states:
  - draft
  - published
  - cancelled
  - archived

transitions:
  - from: draft
    to: published
    rel: publish
    service: event-service
    action: publish_event
    method: POST
    title: Publish this event

  - from: draft
    to: cancelled
    rel: cancel
    service: event-service
    action: cancel_event
    method: POST
    title: Cancel this event

  - from: published
    to: cancelled
    rel: cancel
    service: event-service
    action: cancel_event
    method: POST
    title: Cancel this event

  - from: published
    to: archived
    rel: archive
    service: event-service
    action: archive_event
    method: POST
    title: Archive this event

  - from: cancelled
    to: archived
    rel: archive
    service: event-service
    action: archive_event
    method: POST
    title: Archive this event
