name: ticket
states:
  - available
  - assigned
  - revoked

transitions:
  - from: available
    to: assigned
    rel: assign
    service: ticket-service
    action: assign_ticket
    method: POST
    title: Assign this ticket to a user

  - from: assigned
    to: revoked
    rel: revoke
    service: ticket-service
    action: revoke_ticket
    method: POST
    title: Revoke this ticket

  - from: available
    to: revoked
    rel: revoke
    service: ticket-service
    action: revoke_ticket
    method: POST
    title: Revoke this ticket
